// <auto-generated>
//     Generated by tools/gen_tables.py from the Umoria 5.6 reference sources.
//     Do not edit by hand; edit the generator and re-run it.
//
//     Source: moria/source/player.c
// </auto-generated>

// Copyright (C) 1989-2008 James E. Wilson, Robert A. Koeneke, David J. Grabiner
// Copyright (C) 2026 AIrom contributors
// Licensed under the GNU General Public License v3 or later. See LICENSE.


namespace Airom.Data;

public static partial class GameTables
{
    /// <summary>
    /// The eight playable races. Each shifts the rolled stats and carries its
    /// own build, lifespan and aptitudes.
    /// </summary>
    public static readonly RaceType[] Races = new RaceType[8]
    {
        new("Human", 0, 0, 0, 0, 0, 0, 14, 6, 72, 6, 180, 25, 66, 4, 150, 20, 0, 0, 0, 0, 0, 0, 0, 10, 0, 100, 63),
        new("Half-Elf", -1, 1, 0, 1, -1, 1, 24, 16, 66, 6, 130, 15, 62, 6, 100, 10, 2, 6, 1, -1, -1, 5, 3, 9, 2, 110, 63),
        new("Elf", -1, 2, 1, 1, -2, 1, 75, 75, 60, 4, 100, 6, 54, 4, 80, 6, 5, 8, 1, -2, -5, 15, 6, 8, 3, 120, 31),
        new("Halfling", -2, 2, 1, 3, 1, 1, 21, 12, 36, 3, 60, 3, 33, 3, 50, 3, 15, 12, 4, -5, -10, 20, 18, 6, 4, 110, 11),
        new("Gnome", -1, 2, 0, 2, 1, -2, 50, 40, 42, 3, 90, 6, 39, 3, 75, 3, 10, 6, 3, -3, -8, 12, 12, 7, 4, 125, 15),
        new("Dwarf", 2, -3, 1, -2, 2, -3, 35, 15, 48, 3, 150, 10, 46, 3, 120, 10, 2, 7, -1, 0, 15, 0, 9, 9, 5, 120, 5),
        new("Half-Orc", 2, -1, 0, 0, 1, -4, 11, 4, 66, 1, 150, 5, 62, 1, 120, 5, -3, 0, -1, 3, 12, -5, -3, 10, 3, 110, 13),
        new("Half-Troll", 4, -4, -2, -4, 3, -6, 20, 10, 96, 10, 255, 50, 84, 8, 225, 40, -5, -1, -2, 5, 20, -10, -8, 12, 3, 120, 5),
    };

    /// <summary>
    /// The six classes. Their stat adjustments are applied after the race's,
    /// so a class can pull a stat back down that a race pushed up.
    /// </summary>
    public static readonly ClassType[] Classes = new ClassType[6]
    {
        new("Warrior", 9, 25, 14, 1, 38, 70, 55, 18, 5, -2, -2, 2, 2, -1, 0, 0, 0),
        new("Mage", 0, 30, 16, 2, 20, 34, 20, 36, -5, 3, 0, 1, -2, 1, 1, 30, 1),
        new("Priest", 2, 25, 16, 2, 32, 48, 35, 30, -3, -3, 3, -1, 0, 2, 2, 20, 1),
        new("Rogue", 6, 45, 32, 5, 16, 60, 66, 30, 2, 1, -2, 3, 1, -1, 1, 0, 5),
        new("Ranger", 4, 30, 24, 3, 24, 56, 72, 30, 2, 2, 0, 1, 1, 1, 1, 40, 3),
        new("Paladin", 6, 20, 12, 1, 38, 68, 40, 24, 3, -3, 1, 0, 2, 2, 2, 35, 1),
    };

    /// <summary>
    /// Fragments of a character's history, arranged as a set of linked charts.
    /// Each entry names the chart it belongs to and the chart to continue with,
    /// so rolling walks from one to the next until it runs out.
    /// </summary>
    public static readonly BackgroundType[] Backgrounds = new BackgroundType[128]
    {
        new("You are the illegitimate and unacknowledged child ", 10, 1, 2, 25),
        new("You are the illegitimate but acknowledged child ", 20, 1, 2, 35),
        new("You are one of several children ", 95, 1, 2, 45),
        new("You are the first child ", 100, 1, 2, 50),
        new("of a Serf.  ", 40, 2, 3, 65),
        new("of a Yeoman.  ", 65, 2, 3, 80),
        new("of a Townsman.  ", 80, 2, 3, 90),
        new("of a Guildsman.  ", 90, 2, 3, 105),
        new("of a Landed Knight.  ", 96, 2, 3, 120),
        new("of a Titled Noble.  ", 99, 2, 3, 130),
        new("of a Royal Blood Line.  ", 100, 2, 3, 140),
        new("You are the black sheep of the family.  ", 20, 3, 50, 20),
        new("You are a credit to the family.  ", 80, 3, 50, 55),
        new("You are a well liked child.  ", 100, 3, 50, 60),
        new("Your mother was a Green-Elf.  ", 40, 4, 1, 50),
        new("Your father was a Green-Elf.  ", 75, 4, 1, 55),
        new("Your mother was a Grey-Elf.  ", 90, 4, 1, 55),
        new("Your father was a Grey-Elf.  ", 95, 4, 1, 60),
        new("Your mother was a High-Elf.  ", 98, 4, 1, 65),
        new("Your father was a High-Elf.  ", 100, 4, 1, 70),
        new("You are one of several children ", 60, 7, 8, 50),
        new("You are the only child ", 100, 7, 8, 55),
        new("of a Green-Elf ", 75, 8, 9, 50),
        new("of a Grey-Elf ", 95, 8, 9, 55),
        new("of a High-Elf ", 100, 8, 9, 60),
        new("Ranger.  ", 40, 9, 54, 80),
        new("Archer.  ", 70, 9, 54, 90),
        new("Warrior.  ", 87, 9, 54, 110),
        new("Mage.  ", 95, 9, 54, 125),
        new("Prince.  ", 99, 9, 54, 140),
        new("King.  ", 100, 9, 54, 145),
        new("You are one of several children of a Halfling ", 85, 10, 11, 45),
        new("You are the only child of a Halfling ", 100, 10, 11, 55),
        new("Bum.  ", 20, 11, 3, 55),
        new("Tavern Owner.  ", 30, 11, 3, 80),
        new("Miller.  ", 40, 11, 3, 90),
        new("Home Owner.  ", 50, 11, 3, 100),
        new("Burglar.  ", 80, 11, 3, 110),
        new("Warrior.  ", 95, 11, 3, 115),
        new("Mage.  ", 99, 11, 3, 125),
        new("Clan Elder.  ", 100, 11, 3, 140),
        new("You are one of several children of a Gnome ", 85, 13, 14, 45),
        new("You are the only child of a Gnome ", 100, 13, 14, 55),
        new("Beggar.  ", 20, 14, 3, 55),
        new("Braggart.  ", 50, 14, 3, 70),
        new("Prankster.  ", 75, 14, 3, 85),
        new("Warrior.  ", 95, 14, 3, 100),
        new("Mage.  ", 100, 14, 3, 125),
        new("You are one of two children of a Dwarven ", 25, 16, 17, 40),
        new("You are the only child of a Dwarven ", 100, 16, 17, 50),
        new("Thief.  ", 10, 17, 18, 60),
        new("Prison Guard.  ", 25, 17, 18, 75),
        new("Miner.  ", 75, 17, 18, 90),
        new("Warrior.  ", 90, 17, 18, 110),
        new("Priest.  ", 99, 17, 18, 130),
        new("King.  ", 100, 17, 18, 150),
        new("You are the black sheep of the family.  ", 15, 18, 57, 10),
        new("You are a credit to the family.  ", 85, 18, 57, 50),
        new("You are a well liked child.  ", 100, 18, 57, 55),
        new("Your mother was an Orc, but it is unacknowledged.  ", 25, 19, 20, 25),
        new("Your father was an Orc, but it is unacknowledged.  ", 100, 19, 20, 25),
        new("You are the adopted child ", 100, 20, 2, 50),
        new("Your mother was a Cave-Troll ", 30, 22, 23, 20),
        new("Your father was a Cave-Troll ", 60, 22, 23, 25),
        new("Your mother was a Hill-Troll ", 75, 22, 23, 30),
        new("Your father was a Hill-Troll ", 90, 22, 23, 35),
        new("Your mother was a Water-Troll ", 95, 22, 23, 40),
        new("Your father was a Water-Troll ", 100, 22, 23, 45),
        new("Cook.  ", 5, 23, 62, 60),
        new("Warrior.  ", 95, 23, 62, 55),
        new("Shaman.  ", 99, 23, 62, 65),
        new("Clan Chief.  ", 100, 23, 62, 80),
        new("You have dark brown eyes, ", 20, 50, 51, 50),
        new("You have brown eyes, ", 60, 50, 51, 50),
        new("You have hazel eyes, ", 70, 50, 51, 50),
        new("You have green eyes, ", 80, 50, 51, 50),
        new("You have blue eyes, ", 90, 50, 51, 50),
        new("You have blue-gray eyes, ", 100, 50, 51, 50),
        new("straight ", 70, 51, 52, 50),
        new("wavy ", 90, 51, 52, 50),
        new("curly ", 100, 51, 52, 50),
        new("black hair, ", 30, 52, 53, 50),
        new("brown hair, ", 70, 52, 53, 50),
        new("auburn hair, ", 80, 52, 53, 50),
        new("red hair, ", 90, 52, 53, 50),
        new("blond hair, ", 100, 52, 53, 50),
        new("and a very dark complexion.", 10, 53, 0, 50),
        new("and a dark complexion.", 30, 53, 0, 50),
        new("and an average complexion.", 80, 53, 0, 50),
        new("and a fair complexion.", 90, 53, 0, 50),
        new("and a very fair complexion.", 100, 53, 0, 50),
        new("You have light grey eyes, ", 85, 54, 55, 50),
        new("You have light blue eyes, ", 95, 54, 55, 50),
        new("You have light green eyes, ", 100, 54, 55, 50),
        new("straight ", 75, 55, 56, 50),
        new("wavy ", 100, 55, 56, 50),
        new("black hair, and a fair complexion.", 75, 56, 0, 50),
        new("brown hair, and a fair complexion.", 85, 56, 0, 50),
        new("blond hair, and a fair complexion.", 95, 56, 0, 50),
        new("silver hair, and a fair complexion.", 100, 56, 0, 50),
        new("You have dark brown eyes, ", 99, 57, 58, 50),
        new("You have glowing red eyes, ", 100, 57, 58, 60),
        new("straight ", 90, 58, 59, 50),
        new("wavy ", 100, 58, 59, 50),
        new("black hair, ", 75, 59, 60, 50),
        new("brown hair, ", 100, 59, 60, 50),
        new("a one foot beard, ", 25, 60, 61, 50),
        new("a two foot beard, ", 60, 60, 61, 51),
        new("a three foot beard, ", 90, 60, 61, 53),
        new("a four foot beard, ", 100, 60, 61, 55),
        new("and a dark complexion.", 100, 61, 0, 50),
        new("You have slime green eyes, ", 60, 62, 63, 50),
        new("You have puke yellow eyes, ", 85, 62, 63, 50),
        new("You have blue-bloodshot eyes, ", 99, 62, 63, 50),
        new("You have glowing red eyes, ", 100, 62, 63, 55),
        new("dirty ", 33, 63, 64, 50),
        new("mangy ", 66, 63, 64, 50),
        new("oily ", 100, 63, 64, 50),
        new("sea-weed green hair, ", 33, 64, 65, 50),
        new("bright red hair, ", 66, 64, 65, 50),
        new("dark purple hair, ", 100, 64, 65, 50),
        new("and green ", 25, 65, 66, 50),
        new("and blue ", 50, 65, 66, 50),
        new("and white ", 75, 65, 66, 50),
        new("and black ", 100, 65, 66, 50),
        new("ulcerous skin.", 33, 66, 0, 50),
        new("scabby skin.", 66, 66, 0, 50),
        new("leprous skin.", 100, 66, 0, 50),
    };

    /// <summary>
    /// The five items each class starts with, as object table indices.
    /// </summary>
    public static readonly int[][] StartingItems =
    [
        [344, 365, 123, 30, 103],
        [344, 365, 123, 30, 318],
        [344, 365, 123, 30, 322],
        [344, 365, 123, 30, 318],
        [344, 365, 123, 30, 318],
        [344, 365, 123, 30, 322],
    ];
}
