// <auto-generated>
//     Generated by tools/gen_tables.py from the Umoria 5.6 reference sources.
//     Do not edit by hand; edit the generator and re-run it.
//
//     Source: moria/source/tables.c
// </auto-generated>

// Copyright (C) 1989-2008 James E. Wilson, Robert A. Koeneke, David J. Grabiner
// Copyright (C) 2026 AIrom contributors
// Licensed under the GNU General Public License v3 or later. See LICENSE.


namespace Airom.Data;

public static partial class GameTables
{
    /// <summary>
    /// Store owners. Umoria notes that owners must be added in groups, one
    /// per store, because a store picks its owner by indexing this table in
    /// strides of MAX_STORES.
    /// </summary>
    public static readonly OwnerType[] Owners = new OwnerType[18]
    {
        new("Erick the Honest       (Human)      General Store", 250, 175, 108, 4, 0, 12),
        new("Mauglin the Grumpy     (Dwarf)      Armory", 32000, 200, 112, 4, 5, 5),
        new("Arndal Beast-Slayer    (Half-Elf)   Weaponsmith", 10000, 185, 110, 5, 1, 8),
        new("Hardblow the Humble    (Human)      Temple", 3500, 175, 109, 6, 0, 15),
        new("Ga-nat the Greedy      (Gnome)      Alchemist", 12000, 220, 115, 4, 4, 9),
        new("Valeria Starshine      (Elf)        Magic Shop", 32000, 175, 110, 5, 2, 11),
        new("Andy the Friendly      (Halfling)   General Store", 200, 170, 108, 5, 3, 15),
        new("Darg-Low the Grim      (Human)      Armory", 10000, 190, 111, 4, 0, 9),
        new("Oglign Dragon-Slayer   (Dwarf)      Weaponsmith", 32000, 195, 112, 4, 5, 8),
        new("Gunnar the Paladin     (Human)      Temple", 5000, 185, 110, 5, 0, 23),
        new("Mauser the Chemist     (Half-Elf)   Alchemist", 10000, 190, 111, 5, 1, 8),
        new("Gopher the Great!      (Gnome)      Magic Shop", 20000, 215, 113, 6, 4, 10),
        new("Lyar-el the Comely     (Elf)        General Store", 300, 165, 107, 6, 2, 18),
        new("Mauglim the Horrible   (Half-Orc)   Armory", 3000, 200, 113, 5, 6, 9),
        new("Ithyl-Mak the Beastly  (Half-Troll) Weaponsmith", 3000, 210, 115, 6, 7, 8),
        new("Delilah the Pure       (Half-Elf)   Temple", 25000, 180, 107, 6, 1, 20),
        new("Wizzle the Chaotic     (Halfling)   Alchemist", 10000, 190, 110, 6, 3, 8),
        new("Inglorian the Mage     (Human?)     Magic Shop", 32000, 200, 110, 7, 0, 10),
    };

    /// <summary>
    /// Price multiplier as a percentage, indexed [ownerRace][playerRace].
    /// Dwarves charge half-trolls 135% and their own kind 95%.
    /// </summary>
    public static readonly byte[][] RaceGoldAdjust =
    [
        [100, 105, 105, 110, 113, 115, 120, 125],
        [110, 100, 100, 105, 110, 120, 125, 130],
        [110, 105, 100, 105, 110, 120, 125, 130],
        [115, 110, 105, 95, 105, 110, 115, 130],
        [115, 115, 110, 105, 95, 110, 115, 130],
        [115, 120, 120, 110, 110, 95, 125, 135],
        [115, 120, 125, 115, 115, 130, 110, 115],
        [110, 115, 115, 110, 110, 130, 110, 110],
    ];

    /// <summary>
    /// ObjectList indices each store restocks from, indexed [store][slot].
    /// Repeated entries are deliberate - they weight the random draw.
    /// </summary>
    public static readonly ushort[][] StoreChoice =
    [
        [366, 365, 364, 84, 84, 365, 123, 366, 365, 350, 349, 348, 347, 346, 346, 345, 345, 345, 344, 344, 344, 344, 344, 344, 344, 344],
        [94, 95, 96, 109, 103, 104, 105, 106, 110, 111, 112, 114, 116, 124, 125, 126, 127, 129, 103, 104, 124, 125, 91, 92, 95, 96],
        [29, 30, 34, 37, 45, 49, 57, 58, 59, 65, 67, 68, 73, 74, 75, 77, 79, 80, 81, 83, 29, 30, 80, 83, 80, 83],
        [322, 323, 324, 325, 180, 180, 233, 237, 240, 241, 361, 362, 57, 58, 59, 260, 358, 359, 265, 237, 237, 240, 240, 241, 323, 359],
        [173, 174, 175, 351, 351, 352, 353, 354, 355, 356, 357, 206, 227, 230, 236, 252, 253, 352, 353, 354, 355, 356, 359, 363, 359, 359],
        [318, 141, 142, 153, 164, 167, 168, 140, 319, 320, 320, 321, 269, 270, 282, 286, 287, 292, 293, 294, 295, 308, 269, 290, 319, 282],
    ];

    /// <summary>
    /// Melee blows per round, indexed [strengthBand][dexterityBand].
    /// </summary>
    public static readonly byte[][] BlowsTable =
    [
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 2, 2],
        [1, 1, 1, 2, 2, 3],
        [1, 1, 2, 2, 3, 3],
        [1, 2, 2, 3, 3, 4],
        [1, 2, 2, 3, 4, 4],
        [2, 2, 3, 3, 4, 4],
    ];
}
