// <auto-generated>
//     Generated by tools/gen_tables.py from the Umoria 5.6 reference sources.
//     Do not edit by hand; edit the generator and re-run it.
//
//     Source: moria/source/recall.c
// </auto-generated>

// Copyright (C) 1989-2008 James E. Wilson, Robert A. Koeneke, David J. Grabiner
// Copyright (C) 2026 AIrom contributors
// Licensed under the GNU General Public License v3 or later. See LICENSE.


namespace Airom.Data;

public static partial class GameTables
{
    /// <summary>
    /// What an attack does to the player, indexed by attack_type.
    /// </summary>
    public static readonly string[] AttackEffects =
    [
        "do something undefined", "attack", "weaken", "confuse", "terrify", "shoot flames",
        "shoot acid", "freeze", "shoot lightning", "corrode", "blind", "paralyse",
        "steal money", "steal things", "poison", "reduce dexterity", "reduce constitution",
        "drain intelligence", "drain wisdom", "lower experience", "call for help",
        "disenchant", "eat your food", "absorb light", "absorb charges"
    ];

    /// <summary>
    /// How an attack is delivered, indexed by attack_desc.
    /// </summary>
    public static readonly string[] AttackMethods =
    [
        "make an undefined advance", "hit", "bite", "claw", "sting", "touch", "kick", "gaze",
        "breathe", "spit", "wail", "embrace", "crawl on you", "release spores", "beg",
        "slime you", "crush", "trample", "drool", "insult"
    ];

    /// <summary>
    /// How much a creature wanders, indexed by its random-move bits.
    /// </summary>
    public static readonly string[] HowErratically =
    [
        " not at all", " a bit", "", " quite", " very", " most", " highly", " extremely"
    ];

    /// <summary>
    /// What a creature can do beyond walking and hitting, in the order of the CM_SPECIAL bits.
    /// </summary>
    public static readonly string[] SpecialAbilities =
    [
        "move invisibly", "open doors", "pass through walls", "kill weaker creatures",
        "pick up objects", "breed explosively"
    ];

    /// <summary>
    /// What a creature's spells do, in the order of the CS_SPELLS bits.
    /// </summary>
    public static readonly string[] SpellDescriptions =
    [
        "teleport short distances", "teleport long distances", "teleport its prey",
        "cause light wounds", "cause serious wounds", "paralyse its prey", "induce blindness",
        "confuse", "terrify", "summon a monster", "summon the undead", "slow its prey",
        "drain mana", "unknown 1", "unknown 2"
    ];

    /// <summary>
    /// What a creature breathes, in the order of the CS_BREATHE bits.
    /// </summary>
    public static readonly string[] BreathDescriptions =
    [
        "lightning", "poison gases", "acid", "frost", "fire"
    ];

    /// <summary>
    /// What a creature is hurt by, in the order of the CD_WEAKNESS bits.
    /// </summary>
    public static readonly string[] Weaknesses =
    [
        "frost", "fire", "poison", "acid", "bright light", "rock remover"
    ];
}
