// <auto-generated>
//     Generated by tools/gen_tables.py from the Umoria 5.6 reference sources.
//     Do not edit by hand; edit the generator and re-run it.
//
//     Source: moria/source/store2.c
// </auto-generated>

// Copyright (C) 1989-2008 James E. Wilson, Robert A. Koeneke, David J. Grabiner
// Copyright (C) 2026 AIrom contributors
// Licensed under the GNU General Public License v3 or later. See LICENSE.


namespace Airom.Data;

public static partial class GameTables
{
    /// <summary>
    /// What a shopkeeper says when a price is finally agreed.
    /// </summary>
    public static readonly string[] ShopkeeperAccepts =
    [
        "Done!", "Accepted!", "Fine.", "Agreed!", "Ok.", "Taken!",
        "You drive a hard bargain, but taken.", "You'll force me bankrupt, but it's a deal.",
        "Sigh.  I'll take it.", "My poor sick children may starve, but done!",
        "Finally!  I accept.", "Robbed again.", "A pleasure to do business with you!",
        "My spouse will skin me, but accepted."
    ];

    /// <summary>
    /// What a shopkeeper says when their asking price is their last word. %A1 is the offer and %A2 the asking price.
    /// </summary>
    public static readonly string[] ShopkeeperFinalAsk =
    [
        "%A2 is my final offer; take it or leave it.", "I'll give you no more than %A2.",
        "My patience grows thin.  %A2 is final."
    ];

    /// <summary>
    /// What a shopkeeper says to an offer they mean to haggle over.
    /// </summary>
    public static readonly string[] ShopkeeperCounterAsk =
    [
        "%A1 for such a fine item?  HA!  No less than %A2.",
        "%A1 is an insult!  Try %A2 gold pieces.",
        "%A1?!?  You would rob my poor starving children?",
        "Why, I'll take no less than %A2 gold pieces.", "Ha!  No less than %A2 gold pieces.",
        "Thou knave!  No less than %A2 gold pieces.", "%A1 is far too little, how about %A2?",
        "I paid more than %A1 for it myself, try %A2.",
        "%A1?  Are you mad?!?  How about %A2 gold pieces?",
        "As scrap this would bring %A1.  Try %A2 in gold.",
        "May the fleas of 1000 orcs molest you.  I want %A2.",
        "My mother you can get for %A1, this costs %A2.",
        "May your chickens grow lips.  I want %A2 in gold!",
        "Sell this for such a pittance?  Give me %A2 gold.",
        "May the Balrog find you tasty!  %A2 gold pieces?",
        "Your mother was a Troll!  %A2 or I'll tell."
    ];

    /// <summary>
    /// What a shopkeeper says when their offer for something is final.
    /// </summary>
    public static readonly string[] ShopkeeperFinalOffer =
    [
        "I'll pay no more than %A1; take it or leave it.",
        "You'll get no more than %A1 from me.", "%A1 and that's final."
    ];

    /// <summary>
    /// What a shopkeeper says to a price they mean to haggle down.
    /// </summary>
    public static readonly string[] ShopkeeperCounterOffer =
    [
        "%A2 for that piece of junk?  No more than %A1.",
        "For %A2 I could own ten of those.  Try %A1.", "%A2?  NEVER!  %A1 is more like it.",
        "Let's be reasonable. How about %A1 gold pieces?", "%A1 gold for that junk, no more.",
        "%A1 gold pieces and be thankful for it!", "%A1 gold pieces and not a copper more.",
        "%A2 gold?  HA!  %A1 is more like it.", "Try about %A1 gold.",
        "I wouldn't pay %A2 for your children, try %A1.", "*CHOKE* For that!?  Let's say %A1.",
        "How about %A1?", "That looks war surplus!  Say %A1 gold.",
        "I'll buy it as scrap for %A1.", "%A2 is too much, let us say %A1 gold."
    ];

    /// <summary>
    /// The first half of being thrown out, paired with <see cref="ShopkeeperThrowsOut"/> by index.
    /// </summary>
    public static readonly string[] ShopkeeperLosesTemper =
    [
        "ENOUGH!  You have abused me once too often!",
        "THAT DOES IT!  You shall waste my time no more!",
        "This is getting nowhere.  I'm going home!", "BAH!  No more shall you insult me!",
        "Begone!  I have had enough abuse for one day."
    ];

    /// <summary>
    /// The second half of being thrown out.
    /// </summary>
    public static readonly string[] ShopkeeperThrowsOut =
    [
        "Out of my place!", "out... Out... OUT!!!", "Come back tomorrow.",
        "Leave my place.  Begone!", "Come back when thou art richer."
    ];

    /// <summary>
    /// What a shopkeeper says to an offer that is not worth answering.
    /// </summary>
    public static readonly string[] ShopkeeperInsulted =
    [
        "You will have to do better than that!", "That's an insult!",
        "Do you wish to do business or not?", "Hah!  Try again.", "Ridiculous!",
        "You've got to be kidding!", "You'd better be kidding!", "You try my patience.",
        "I don't hear you.", "Hmmm, nice weather we're having."
    ];

    /// <summary>
    /// What a shopkeeper says to an offer that makes no sense at all.
    /// </summary>
    public static readonly string[] ShopkeeperMishears =
    [
        "I must have heard you wrong.", "What was that?", "I'm sorry, say that again.",
        "What did you say?", "Sorry, what was that again?"
    ];
}
