#!/usr/bin/env python3
"""Generate AIrom's static data tables from the Umoria 5.6 C sources.

The object and monster tables are ~700 rows of C struct initialisers. Hand
transcription would be both tedious and unverifiable, so they are generated
instead: this script is the record of how each C field maps to each C# field,
and re-running it against the reference sources reproduces the output exactly.

Usage:
    python tools/gen_tables.py [--moria PATH] [--check]

--check regenerates into memory and fails if the committed files differ,
which is what CI would run to prove the tables were not hand-edited.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_MORIA = Path("C:/code/moria")

HEADER = """// <auto-generated>
//     Generated by tools/gen_tables.py from the Umoria 5.6 reference sources.
//     Do not edit by hand; edit the generator and re-run it.
//
//     Source: {source}
// </auto-generated>

// Copyright (C) 1989-2008 James E. Wilson, Robert A. Koeneke, David J. Grabiner
// Copyright (C) 2026 AIrom contributors
// Licensed under the GNU General Public License v3 or later. See LICENSE.

"""


# ---------------------------------------------------------------- C parsing


def parse_defines(text: str) -> dict[str, int]:
    """Collect simple integer #defines so table rows can reference TV_* names."""
    out: dict[str, int] = {}
    pattern = re.compile(
        r"^#define\s+([A-Za-z_]\w*)\s+(-?(?:0[xX][0-9a-fA-F]+|\d+))[LlUu]*\s*(?:/\*.*)?$"
    )
    for line in text.splitlines():
        m = pattern.match(line.strip())
        if m:
            out[m.group(1)] = int(m.group(2), 0)
    return out


def strip_comments(text: str) -> str:
    return re.sub(r"/\*.*?\*/", " ", text, flags=re.S)


def _evaluate(expression: str, defined: set[str]) -> bool:
    """Evaluate a #if expression treating every unknown symbol as undefined."""
    expr = re.sub(
        r"defined\s*\(\s*(\w+)\s*\)",
        lambda m: "1" if m.group(1) in defined else "0",
        expression,
    )
    expr = re.sub(r"defined\s+(\w+)", lambda m: "1" if m.group(1) in defined else "0", expr)
    expr = expr.replace("||", " or ").replace("&&", " and ").replace("!", " not ")
    expr = re.sub(r"\b(?!or\b|and\b|not\b)[A-Za-z_]\w*\b", "0", expr)
    expr = re.sub(r"\b(\d+)[LlUu]+\b", r"\1", expr)
    try:
        return bool(eval(expr, {"__builtins__": {}}, {}))  # noqa: S307 - fixed inputs
    except Exception as exc:  # pragma: no cover - surfaces a source we cannot read
        raise ValueError("cannot evaluate #if " + expression) from exc


def select_branches(text: str, defined: set[str] | None = None) -> str:
    """Resolve #if/#ifdef/#else/#endif, keeping only the branches that apply.

    The tables are not plain data: treasure.c gives the secret door row one
    definition under ATARI_ST and another otherwise, and the whole array is
    replaced by a pointer under MACGAME. Parsing without resolving these picks
    up both branches and silently corrupts the row structure, so the generator
    has to make the same choices a compiler would.

    Every platform symbol is treated as undefined, which selects the portable
    build - the one AIrom is derived from.
    """
    defined = defined or set()
    out: list[str] = []
    # Each entry is [currently_taken, any_branch_taken_yet, parent_is_live].
    stack: list[list[bool]] = []

    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        live = all(frame[0] for frame in stack)

        if stripped.startswith("#if"):
            parent_live = live
            if stripped.startswith("#ifdef"):
                taken = stripped.split(None, 1)[1].split()[0] in defined
            elif stripped.startswith("#ifndef"):
                taken = stripped.split(None, 1)[1].split()[0] not in defined
            else:
                taken = _evaluate(stripped[3:].strip(), defined)
            stack.append([taken and parent_live, taken, parent_live])
            continue

        if stripped.startswith("#elif") and stack:
            frame = stack[-1]
            taken = (not frame[1]) and _evaluate(stripped[5:].strip(), defined)
            frame[0] = taken and frame[2]
            frame[1] = frame[1] or taken
            continue

        if stripped.startswith("#else") and stack:
            frame = stack[-1]
            frame[0] = (not frame[1]) and frame[2]
            frame[1] = True
            continue

        if stripped.startswith("#endif") and stack:
            stack.pop()
            continue

        if live:
            out.append(line)

    if stack:
        raise ValueError("unbalanced preprocessor conditionals")
    return "".join(out)


def code_positions(text: str, begin: int = 0):
    """Yield (index, char) for characters that are real code.

    The contents of string and character literals are skipped. This matters more
    than it looks: the object table gives bows the glyph '}' and arrows '{', so
    any brace counting that ignores literals terminates the array 74 rows in.
    """
    in_string = False
    in_char = False
    escaped = False
    for i in range(begin, len(text)):
        ch = text[i]
        if escaped:
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            continue
        if in_string:
            in_string = ch != '"'
            continue
        if in_char:
            in_char = ch != "'"
            continue
        if ch == '"':
            in_string = True
            continue
        if ch == "'":
            in_char = True
            continue
        yield i, ch


def extract_initialiser(text: str, declaration: str) -> str:
    """Return the body between the braces of `<declaration> = { ... };`."""
    start = text.index(declaration)
    brace = text.index("{", start)
    depth = 0
    for i, ch in code_positions(text, brace):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[brace + 1 : i]
    raise ValueError("unterminated initialiser for " + declaration)


def split_rows(body: str) -> list[str]:
    """Split a struct-array body into its top-level {...} rows."""
    rows: list[str] = []
    depth = 0
    start = 0
    for i, ch in code_positions(body):
        if ch == "{":
            if depth == 0:
                start = i + 1
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                rows.append(body[start:i])
    return rows


def split_fields(row: str) -> list[str]:
    """Split one row into fields on top-level commas, keeping {a,b} groups whole."""
    fields: list[str] = []
    depth = 0
    current: list[str] = []
    in_string = False
    in_char = False
    escaped = False
    for ch in row:
        if escaped:
            current.append(ch)
            escaped = False
            continue
        if ch == "\\" and (in_string or in_char):
            current.append(ch)
            escaped = True
            continue
        if in_string:
            current.append(ch)
            in_string = ch != '"'
            continue
        if in_char:
            current.append(ch)
            in_char = ch != "'"
            continue
        if ch == '"':
            in_string = True
        elif ch == "'":
            in_char = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        elif ch == "," and depth == 0:
            fields.append("".join(current).strip())
            current = []
            continue
        current.append(ch)
    if "".join(current).strip():
        fields.append("".join(current).strip())
    return fields


C_ESCAPES = {"n": "\n", "t": "\t", "0": "\0", "\\": "\\", "'": "'", '"': '"'}


def c_string(field: str) -> str:
    """Convert a C string literal to a C# one."""
    if not (field.startswith('"') and field.endswith('"')):
        raise ValueError("expected string literal, got " + repr(field))
    raw = field[1:-1]
    out: list[str] = []
    i = 0
    while i < len(raw):
        if raw[i] == "\\" and i + 1 < len(raw):
            out.append(C_ESCAPES.get(raw[i + 1], raw[i + 1]))
            i += 2
        else:
            out.append(raw[i])
            i += 1
    value = "".join(out)
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_number(field: str, defines: dict[str, int]) -> int:
    """Evaluate a numeric field: literal, char literal, or #define name."""
    f = field.strip().rstrip("LlUu")
    if f.startswith("'") and f.endswith("'"):
        body = f[1:-1]
        if body.startswith("\\"):
            return ord(C_ESCAPES.get(body[1], body[1]))
        return ord(body)
    if f in defines:
        return defines[f]
    negate = f.startswith("-")
    if negate:
        f = f[1:]
    try:
        value = int(f, 0)
    except ValueError as exc:
        raise ValueError("cannot evaluate " + repr(field)) from exc
    return -value if negate else value


def c_array(field: str, defines: dict[str, int], expected: int) -> list[int]:
    inner = field.strip()
    if not (inner.startswith("{") and inner.endswith("}")):
        raise ValueError("expected brace group, got " + repr(field))
    parts = [p for p in split_fields(inner[1:-1]) if p]
    values = [c_number(p, defines) for p in parts]
    if len(values) != expected:
        raise ValueError(
            "expected {0} values in {1!r}, got {2}".format(expected, field, len(values))
        )
    return values


# ---------------------------------------------------------------- emitting


def char_literal(code: int) -> str:
    ch = chr(code)
    if ch == "'":
        return "'\\''"
    if ch == "\\":
        return "'\\\\'"
    if ch == "\0":
        return "'\\0'"
    if 32 <= code < 127:
        return "'" + ch + "'"
    return "'\\u{0:04X}'".format(code)


def gen_objects(moria: Path) -> str:
    defines = parse_defines(
        (moria / "source" / "constant.h").read_text(encoding="latin-1")
    )
    text = (moria / "source" / "treasure.c").read_text(encoding="latin-1")
    body = extract_initialiser(strip_comments(select_branches(text)), "object_list[MAX_OBJECTS]")
    rows = split_rows(body)

    expected = defines["MAX_OBJECTS"]
    if len(rows) != expected:
        raise SystemExit(
            "object_list: parsed {0} rows, MAX_OBJECTS is {1}".format(len(rows), expected)
        )

    lines = [
        HEADER.format(source="moria/source/treasure.c"),
        "namespace Airom.Data;",
        "",
        "public static partial class GameTables",
        "{",
        "    /// <summary>",
        "    /// Every object in the game, indexed exactly as Umoria's object_list.",
        "    /// Indices are load-bearing: save files, the dungeon generator and the",
        "    /// OBJ_* constants all refer to rows by position.",
        "    /// </summary>",
        "    public static readonly TreasureType[] ObjectList = new TreasureType[{0}]".format(
            expected
        ),
        "    {",
    ]

    for index, row in enumerate(rows):
        f = split_fields(row)
        if len(f) != 15:
            raise SystemExit(
                "object_list row {0}: expected 15 fields, got {1}: {2}".format(
                    index, len(f), f
                )
            )
        name = c_string(f[0])
        flags = c_number(f[1], defines) & 0xFFFFFFFF
        tval = c_number(f[2], defines)
        tchar = c_number(f[3], defines)
        p1 = c_number(f[4], defines)
        cost = c_number(f[5], defines)
        subval = c_number(f[6], defines)
        number = c_number(f[7], defines)
        weight = c_number(f[8], defines)
        tohit = c_number(f[9], defines)
        todam = c_number(f[10], defines)
        ac = c_number(f[11], defines)
        toac = c_number(f[12], defines)
        damage = c_array(f[13], defines, 2)
        level = c_number(f[14], defines)

        lines.append("        // {0}".format(index))
        lines.append(
            "        new({0}, 0x{1:08X}u, {2}, {3}, {4}, {5}, {6}, {7}, {8}, "
            "{9}, {10}, {11}, {12}, {13}, {14}, {15}),".format(
                name,
                flags,
                tval,
                char_literal(tchar),
                p1,
                cost,
                subval,
                number,
                weight,
                tohit,
                todam,
                ac,
                toac,
                damage[0],
                damage[1],
                level,
            )
        )

    lines += ["    };", "}", ""]
    return "\n".join(lines)


def gen_monsters(moria: Path) -> str:
    defines = parse_defines(
        (moria / "source" / "constant.h").read_text(encoding="latin-1")
    )
    text = (moria / "source" / "monsters.c").read_text(encoding="latin-1")
    body = extract_initialiser(strip_comments(select_branches(text)), "c_list[MAX_CREATURES]")
    rows = split_rows(body)

    expected = defines["MAX_CREATURES"]
    if len(rows) != expected:
        raise SystemExit(
            "c_list: parsed {0} rows, MAX_CREATURES is {1}".format(len(rows), expected)
        )

    lines = [
        HEADER.format(source="moria/source/monsters.c"),
        "namespace Airom.Data;",
        "",
        "public static partial class GameTables",
        "{",
        "    /// <summary>",
        "    /// Every monster in the game, indexed exactly as Umoria's c_list.",
        "    /// Indices are load-bearing: save files and the monster memory refer",
        "    /// to rows by position.",
        "    /// </summary>",
        "    public static readonly CreatureType[] CreatureList = new CreatureType[{0}]".format(
            expected
        ),
        "    {",
    ]

    for index, row in enumerate(rows):
        f = split_fields(row)
        if len(f) != 13:
            raise SystemExit(
                "c_list row {0}: expected 13 fields, got {1}: {2}".format(index, len(f), f)
            )
        name = c_string(f[0])
        cmove = c_number(f[1], defines) & 0xFFFFFFFF
        spells = c_number(f[2], defines) & 0xFFFFFFFF
        cdefense = c_number(f[3], defines)
        mexp = c_number(f[4], defines)
        sleep = c_number(f[5], defines)
        aaf = c_number(f[6], defines)
        ac = c_number(f[7], defines)
        speed = c_number(f[8], defines)
        cchar = c_number(f[9], defines)
        hd = c_array(f[10], defines, 2)
        damage = c_array(f[11], defines, 4)
        level = c_number(f[12], defines)

        lines.append("        // {0}".format(index))
        lines.append(
            "        new({0}, 0x{1:08X}u, 0x{2:08X}u, 0x{3:04X}, {4}, {5}, {6}, {7}, "
            "{8}, {9}, {10}, {11}, [{12}], {13}),".format(
                name,
                cmove,
                spells,
                cdefense,
                mexp,
                sleep,
                aaf,
                ac,
                speed,
                char_literal(cchar),
                hd[0],
                hd[1],
                ", ".join(str(d) for d in damage),
                level,
            )
        )

    lines += ["    };", "}", ""]
    return "\n".join(lines)


def _tables_source(moria: Path) -> tuple[str, dict[str, int]]:
    defines = parse_defines(
        (moria / "source" / "constant.h").read_text(encoding="latin-1")
    )
    text = (moria / "source" / "tables.c").read_text(encoding="latin-1")
    return strip_comments(select_branches(text)), defines


def _string_array(body: str) -> list[str]:
    """Parse a flat array of C string literals."""
    return [c_string(f) for f in split_fields(body) if f]


def _matrix(body: str, defines: dict[str, int], rows: int, cols: int) -> list[list[int]]:
    parsed = split_rows(body)
    if len(parsed) != rows:
        raise SystemExit("expected {0} rows, got {1}".format(rows, len(parsed)))
    out = []
    for row in parsed:
        values = [c_number(f, defines) for f in split_fields(row) if f]
        if len(values) != cols:
            raise SystemExit("expected {0} columns, got {1}".format(cols, len(values)))
        out.append(values)
    return out


def _emit_matrix(lines: list[str], name: str, kind: str, doc: list[str], data) -> None:
    lines.extend(doc)
    lines.append("    public static readonly {0}[][] {1} =".format(kind, name))
    lines.append("    [")
    for row in data:
        lines.append("        [" + ", ".join(str(v) for v in row) + "],")
    lines.append("    ];")
    lines.append("")


def _emit_strings(lines: list[str], name: str, doc: list[str], values: list[str]) -> None:
    lines.extend(doc)
    lines.append("    public static readonly string[] {0} =".format(name))
    lines.append("    [")
    line = "        "
    for value in values:
        piece = value + ", "
        if len(line) + len(piece) > 96:
            lines.append(line.rstrip())
            line = "        "
        line += piece
    if line.strip():
        lines.append(line.rstrip().rstrip(","))
    lines.append("    ];")
    lines.append("")


NAME_ARRAYS = [
    ("colors", "Colors", "MAX_COLORS", [
        "    /// <summary>",
        "    /// Potion appearances. magic_init() shuffles these at game start, so the",
        "    /// array is mutable and the first three entries must stay put - slime",
        "    /// mould juice, apple juice and water are fixed.",
        "    /// </summary>",
    ]),
    ("mushrooms", "Mushrooms", "MAX_MUSH", [
        "    /// <summary>Mushroom appearances; shuffled by magic_init().</summary>",
    ]),
    ("woods", "Woods", "MAX_WOODS", [
        "    /// <summary>Staff appearances; shuffled by magic_init().</summary>",
    ]),
    ("metals", "Metals", "MAX_METALS", [
        "    /// <summary>Wand appearances; shuffled by magic_init().</summary>",
    ]),
    ("rocks", "Rocks", "MAX_ROCKS", [
        "    /// <summary>Ring appearances; shuffled by magic_init().</summary>",
    ]),
    ("amulets", "Amulets", "MAX_AMULETS", [
        "    /// <summary>Amulet appearances; shuffled by magic_init().</summary>",
    ]),
    ("syllables", "Syllables", "MAX_SYLLABLES", [
        "    /// <summary>",
        "    /// Fragments assembled into the nonsense titles printed on unidentified",
        "    /// scrolls. magic_init() builds MAX_TITLES names from these.",
        "    /// </summary>",
    ]),
]


def gen_names(moria: Path) -> str:
    text, defines = _tables_source(moria)
    lines = [
        HEADER.format(source="moria/source/tables.c"),
        "namespace Airom.Data;",
        "",
        "public static partial class GameTables",
        "{",
    ]

    for c_name, cs_name, size_macro, doc in NAME_ARRAYS:
        body = extract_initialiser(text, "{0}[{1}]".format(c_name, size_macro))
        values = _string_array(body)
        expected = defines[size_macro]
        if len(values) != expected:
            raise SystemExit(
                "{0}: parsed {1} entries, {2} is {3}".format(
                    c_name, len(values), size_macro, expected
                )
            )
        _emit_strings(lines, cs_name, doc, values)

    # The names an enchantment adds to an item - "of Slay Dragon", "of Westernesse"
    # - live in treasure.c beside the objects rather than in tables.c.
    treasure = strip_comments(
        select_branches(
            (moria / "source" / "treasure.c").read_text(encoding="latin-1")
        )
    )
    body = extract_initialiser(treasure, "special_names[SN_ARRAY_SIZE]")
    # The first entry is a null pointer rather than a string: nothing is added
    # to the name of an item with no enchantment.
    values = [
        '""' if f.strip() == "CNIL" else c_string(f)
        for f in split_fields(body)
        if f
    ]
    expected = defines["SN_ARRAY_SIZE"]
    if len(values) != expected:
        raise SystemExit(
            "special_names: parsed {0} entries, SN_ARRAY_SIZE is {1}".format(
                len(values), expected
            )
        )
    _emit_strings(
        lines,
        "SpecialNames",
        [
            "    /// <summary>",
            "    /// What an enchantment adds to an item's name, indexed by its",
            "    /// <see cref=\"SpecialName\"/>. The first entry is the empty string, so an",
            "    /// unenchanted item indexes it harmlessly.",
            "    /// </summary>",
        ],
        values,
    )

    lines[-1:] = ["}", ""]
    return "\n".join(lines)


def gen_misc_tables(moria: Path) -> str:
    text, defines = _tables_source(moria)

    owners_body = extract_initialiser(text, "owners[MAX_OWNERS]")
    owner_rows = split_rows(owners_body)
    if len(owner_rows) != defines["MAX_OWNERS"]:
        raise SystemExit(
            "owners: parsed {0} rows, MAX_OWNERS is {1}".format(
                len(owner_rows), defines["MAX_OWNERS"]
            )
        )

    lines = [
        HEADER.format(source="moria/source/tables.c"),
        "namespace Airom.Data;",
        "",
        "public static partial class GameTables",
        "{",
        "    /// <summary>",
        "    /// Store owners. Umoria notes that owners must be added in groups, one",
        "    /// per store, because a store picks its owner by indexing this table in",
        "    /// strides of MAX_STORES.",
        "    /// </summary>",
        "    public static readonly OwnerType[] Owners = new OwnerType[{0}]".format(
            defines["MAX_OWNERS"]
        ),
        "    {",
    ]
    for index, row in enumerate(owner_rows):
        f = split_fields(row)
        if len(f) != 7:
            raise SystemExit(
                "owners row {0}: expected 7 fields, got {1}".format(index, len(f))
            )
        values = [c_number(x, defines) for x in f[1:]]
        lines.append(
            "        new({0}, {1}),".format(
                c_string(f[0]), ", ".join(str(v) for v in values)
            )
        )
    lines += ["    };", ""]

    _emit_matrix(
        lines,
        "RaceGoldAdjust",
        "byte",
        [
            "    /// <summary>",
            "    /// Price multiplier as a percentage, indexed [ownerRace][playerRace].",
            "    /// Dwarves charge half-trolls 135% and their own kind 95%.",
            "    /// </summary>",
        ],
        _matrix(
            extract_initialiser(text, "rgold_adj[MAX_RACES][MAX_RACES]"),
            defines,
            defines["MAX_RACES"],
            defines["MAX_RACES"],
        ),
    )

    _emit_matrix(
        lines,
        "StoreChoice",
        "ushort",
        [
            "    /// <summary>",
            "    /// ObjectList indices each store restocks from, indexed [store][slot].",
            "    /// Repeated entries are deliberate - they weight the random draw.",
            "    /// </summary>",
        ],
        _matrix(
            extract_initialiser(text, "store_choice[MAX_STORES][STORE_CHOICES]"),
            defines,
            defines["MAX_STORES"],
            defines["STORE_CHOICES"],
        ),
    )

    _emit_matrix(
        lines,
        "BlowsTable",
        "byte",
        [
            "    /// <summary>",
            "    /// Melee blows per round, indexed [strengthBand][dexterityBand].",
            "    /// </summary>",
        ],
        _matrix(extract_initialiser(text, "blows_table[7][6]"), defines, 7, 6),
    )

    lines[-1:] = ["}", ""]
    return "\n".join(lines)



def _player_source(moria):
    defines = parse_defines(
        (moria / "source" / "constant.h").read_text(encoding="latin-1")
    )
    text = (moria / "source" / "player.c").read_text(encoding="latin-1")
    return strip_comments(select_branches(text)), defines


def _emit_rows(lines, declaration, kind, expected, fields, text, defines, doc):
    body = extract_initialiser(text, declaration)
    rows = split_rows(body)
    if len(rows) != expected:
        raise SystemExit(
            "{0}: parsed {1} rows, expected {2}".format(declaration, len(rows), expected)
        )

    lines.extend(doc)
    lines.append(
        "    public static readonly {0}[] {1} = new {0}[{2}]".format(kind[0], kind[1], expected)
    )
    lines.append("    {")

    for index, row in enumerate(rows):
        f = split_fields(row)
        if len(f) != fields:
            raise SystemExit(
                "{0} row {1}: expected {2} fields, got {3}".format(
                    declaration, index, fields, len(f)
                )
            )
        values = [c_string(f[0])]
        values += [str(c_number(x, defines)) for x in f[1:]]
        lines.append("        new(" + ", ".join(values) + "),")

    lines += ["    };", ""]


def gen_player(moria):
    text, defines = _player_source(moria)

    lines = [
        HEADER.format(source="moria/source/player.c"),
        "namespace Airom.Data;",
        "",
        "public static partial class GameTables",
        "{",
    ]

    _emit_rows(
        lines, "race[MAX_RACES]", ("RaceType", "Races"), defines["MAX_RACES"], 28,
        text, defines,
        [
            "    /// <summary>",
            "    /// The eight playable races. Each shifts the rolled stats and carries its",
            "    /// own build, lifespan and aptitudes.",
            "    /// </summary>",
        ],
    )

    _emit_rows(
        lines, "class[MAX_CLASS]", ("ClassType", "Classes"), defines["MAX_CLASS"], 18,
        text, defines,
        [
            "    /// <summary>",
            "    /// The six classes. Their stat adjustments are applied after the race's,",
            "    /// so a class can pull a stat back down that a race pushed up.",
            "    /// </summary>",
        ],
    )

    _emit_rows(
        lines, "background[MAX_BACKGROUND]", ("BackgroundType", "Backgrounds"),
        defines["MAX_BACKGROUND"], 5, text, defines,
        [
            "    /// <summary>",
            "    /// Fragments of a character's history, arranged as a set of linked charts.",
            "    /// Each entry names the chart it belongs to and the chart to continue with,",
            "    /// so rolling walks from one to the next until it runs out.",
            "    /// </summary>",
        ],
    )

    # The class titles are a class-by-level grid of strings.
    body = extract_initialiser(text, "player_title[MAX_CLASS][MAX_PLAYER_LEVEL]")
    rows = split_rows(body)
    if len(rows) != defines["MAX_CLASS"]:
        raise SystemExit(
            "player_title: parsed {0} rows, MAX_CLASS is {1}".format(
                len(rows), defines["MAX_CLASS"]
            )
        )

    lines += [
        "    /// <summary>",
        "    /// What a character of each class is called at each level, indexed",
        "    /// [class][level - 1]. The rank shown beside the race and class.",
        "    /// </summary>",
        "    public static readonly string[][] ClassTitles =",
        "    [",
    ]
    for row in rows:
        titles = [c_string(f) for f in split_fields(row) if f]
        if len(titles) != defines["MAX_PLAYER_LEVEL"]:
            raise SystemExit(
                "player_title row: expected {0} titles, got {1}".format(
                    defines["MAX_PLAYER_LEVEL"], len(titles)
                )
            )
        line = "        ["
        for title in titles:
            if len(line) + len(title) + 2 > 96:
                lines.append(line.rstrip())
                line = "            "
            line += title + ", "
        lines.append(line.rstrip().rstrip(",") + "],")
    lines += ["    ];", ""]

    # How much experience each level costs, before the class multiplier.
    body = extract_initialiser(text, "player_exp[MAX_PLAYER_LEVEL]")
    values = [str(c_number(f, defines)) for f in split_fields(body) if f]
    if len(values) != defines["MAX_PLAYER_LEVEL"]:
        raise SystemExit(
            "player_exp: parsed {0} entries, MAX_PLAYER_LEVEL is {1}".format(
                len(values), defines["MAX_PLAYER_LEVEL"]
            )
        )
    lines += [
        "    /// <summary>",
        "    /// Experience needed for each level, before the class multiplier is",
        "    /// applied. Mirrors player_exp[].",
        "    /// </summary>",
        "    public static readonly int[] PlayerExperience =",
        "    [",
    ]
    line = "        "
    for value in values:
        piece = value + ", "
        if len(line) + len(piece) > 96:
            lines.append(line.rstrip())
            line = "        "
        line += piece
    lines.append(line.rstrip().rstrip(","))
    lines += ["    ];", ""]

    # What each class gains per level at fighting, shooting, using a device,
    # disarming and saving. In player.c rather than tables.c, like the rest of
    # the player data.
    _emit_matrix(
        lines,
        "ClassLevelAdjust",
        "short",
        [
            "    /// <summary>",
            "    /// What each class gains per level, in the five things a level improves:",
            "    /// fighting, shooting, using a magical device, disarming, and saving",
            "    /// throws. Mirrors class_level_adj[][].",
            "    /// </summary>",
        ],
        _matrix(
            extract_initialiser(text, "class_level_adj[MAX_CLASS][MAX_LEV_ADJ]"),
            defines,
            defines["MAX_CLASS"],
            defines["MAX_LEV_ADJ"],
        ),
    )

    body = extract_initialiser(text, "player_init[MAX_CLASS][5]")
    rows = split_rows(body)
    lines += [
        "    /// <summary>",
        "    /// The five items each class starts with, as object table indices.",
        "    /// </summary>",
        "    public static readonly int[][] StartingItems =",
        "    [",
    ]
    for row in rows:
        values = [str(c_number(x, defines)) for x in split_fields(row) if x]
        lines.append("        [" + ", ".join(values) + "],")
    lines += ["    ];", ""]

    lines[-1:] = ["}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------- driver

TARGETS = {
    "src/Airom/Data/GameTables.Objects.g.cs": gen_objects,
    "src/Airom/Data/GameTables.Monsters.g.cs": gen_monsters,
    "src/Airom/Data/GameTables.Names.g.cs": gen_names,
    "src/Airom/Data/GameTables.Misc.g.cs": gen_misc_tables,
    "src/Airom/Data/GameTables.Player.g.cs": gen_player,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--moria", type=Path, default=DEFAULT_MORIA)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not (args.moria / "source" / "treasure.c").exists():
        print("reference sources not found under " + str(args.moria), file=sys.stderr)
        return 2

    repo = Path(__file__).resolve().parent.parent
    failed = False
    for relative, generate in TARGETS.items():
        content = generate(args.moria)
        path = repo / relative
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if existing.replace("\r\n", "\n") != content:
                print("STALE: " + relative, file=sys.stderr)
                failed = True
            else:
                print("ok: " + relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
            print("wrote {0} ({1} lines)".format(relative, content.count("\n")))

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
